image: 
  file: .gitpod.dockerfile
ports: 
    - port: 3000
      onOpen: open-browser
      visibility: public
    - port: 3001
      onOpen: open-preview
      visibility: public
    - port: 5432
      onOpen: ignore
      visibility: public
tasks:
    - init: >
        (cp -n .env.example .env || true) &&
        psql -U gitpod -c 'CREATE DATABASE example;' &&
        psql -U gitpod -c 'CREATE EXTENSION unaccent;' -d example &&
        psql -c "ALTER USER gitpod PASSWORD 'postgres';" &&
        node ./docs/assets/welcome.js

vscode:
  extensions:
    - cweijan.vscode-database-client2
